### ISSUE TITLE
i'm just starting your pluralsight firebase course. Its the best! - but it looks like they changed the layout of the site? 

### ISSUE THREAD

**Issue by spencer1573** [joeeames/FirebaseFundamentalsCourse#2]
is this going to effect things a lot in the course?
![screen shot 2016-05-20 at 3 52 32 pm](https://cloud.githubusercontent.com/assets/4762850/15443144/2fa716aa-1ea3-11e6-89ab-e07a7cd11028.png)

**Comment by joeeames** [comment]
not that I can tell. So far it looks like the API's themselves haven't changed at all. They have added a new analysis feature to the admin tools that I don't cover, but I haven't seen anything else that is actually difference. To be honest, what I have read doesn't sound at all like a "major upgrade" to me. but it might be enough small changes that an enterprise customer will find it overall to be "major". but the programming interface seems to be completely unchanged.

**Comment by spencer1573** [comment]
Thanks!
